// Runs the legacy engine and engine-v2 on the same HTS lines and countries and writes a
// report of every difference, grouped by cause, to tariffs/engine-v2/COMPARISON.md.
//
//   npx tsx scripts/engine-v2/compare-engines.ts [--all]
//
// By default a deterministic sample of lines is used; --all runs every 8/10-digit line.
import { writeFileSync } from "fs"
import { join } from "path"
import { calculate } from "../../tariffs/engine-v2/calculate"
import { AllRules } from "../../tariffs/engine-v2/data"
import { loadHtsLines } from "../../testing/engine-v2/hts-fixture"
import { legacyCalculate } from "../../testing/engine-v2/legacy-adapter"

const AS_OF = "2026-04-10" // inside 2026 Rev 5, the revision the legacy data reflects
const CUSTOMS_VALUE = 10_000
const UNITS = 100
const COUNTRIES = ["CN", "HK", "DE", "FR", "JP", "KR", "GB", "CA", "MX", "RU", "VN", "IN", "BR", "CH"]
// Chapters with the most Chapter 99 activity get sampled more densely
const DENSE_CHAPTERS = new Set(["44", "72", "73", "74", "76", "84", "85", "87", "94"])

interface Difference {
  htsno: string
  country: string
  legacyTotal: number
  v2Total: number
  onlyLegacy: string[]
  onlyV2: string[]
}

const main = async () => {
  const all = process.argv.includes("--all")
  const lines = (await loadHtsLines()).filter(
    (line, i) => all || i % 10 === 0 || (DENSE_CHAPTERS.has(line.htsno.slice(0, 2)) && i % 3 === 0),
  )

  const started = Date.now()
  let runs = 0
  let totalsMatch = 0
  const differences: Difference[] = []

  for (const { htsno, rates } of lines) {
    for (const country of COUNTRIES) {
      runs++
      const legacy = legacyCalculate(htsno, rates, country, CUSTOMS_VALUE, UNITS)
      const v2 = calculate(AllRules, {
        htsCode: htsno,
        country,
        asOf: AS_OF,
        customsValue: CUSTOMS_VALUE,
        quantity: UNITS,
        baseRates: { general: rates.general, special: rates.special, other: rates.other },
      })
      const v2Codes = v2.lines.filter((l) => l.status === "applies").map((l) => l.code)
      const onlyLegacy = legacy.activeCodes.filter((c) => !v2Codes.includes(c)).sort()
      const onlyV2 = v2Codes.filter((c) => !legacy.activeCodes.includes(c)).sort()
      const sameTotal = Math.abs(legacy.totalDuty - v2.totalDuty) < 0.01
      if (sameTotal) totalsMatch++
      if (!sameTotal || onlyLegacy.length || onlyV2.length) {
        differences.push({
          htsno,
          country,
          legacyTotal: legacy.totalDuty,
          v2Total: v2.totalDuty,
          onlyLegacy,
          onlyV2,
        })
      }
    }
  }

  // Group differences by which headings differ and in which direction the total moved
  const groups = new Map<string, Difference[]>()
  for (const d of differences) {
    const delta = d.v2Total - d.legacyTotal
    const direction = Math.abs(delta) < 0.01 ? "same total" : delta > 0 ? "v2 higher" : "v2 lower"
    const signature = `legacy only: ${d.onlyLegacy.join(", ") || "–"} | v2 only: ${d.onlyV2.join(", ") || "–"} | ${direction}`
    groups.set(signature, [...(groups.get(signature) ?? []), d])
  }
  const sorted = Array.from(groups).sort((a, b) => b[1].length - a[1].length)

  const money = (n: number) => `$${n.toFixed(2)}`
  const report = [
    "# Engine comparison: legacy vs engine-v2",
    "",
    "Generated by `scripts/engine-v2/compare-engines.ts`. Don't edit by hand.",
    "",
    `- As-of date for engine-v2: ${AS_OF} (2026 Rev 5)`,
    `- Base rates: current USITC export (may differ slightly from Rev 5 for a few lines)`,
    `- Customs value ${money(CUSTOMS_VALUE)}, quantity ${UNITS}, no answers given (both engines use their defaults)`,
    `- Countries: ${COUNTRIES.join(", ")}`,
    `- HTS lines: ${lines.length}${all ? " (all)" : " (sample)"}`,
    "",
    "## Summary",
    "",
    `| | Count | Share |`,
    `|---|---|---|`,
    `| Calculations | ${runs} | 100% |`,
    `| Same total duty | ${totalsMatch} | ${((totalsMatch / runs) * 100).toFixed(1)}% |`,
    `| Any difference (total or headings) | ${differences.length} | ${((differences.length / runs) * 100).toFixed(1)}% |`,
    `| Distinct kinds of difference | ${groups.size} | |`,
    "",
    `Runtime: ${((Date.now() - started) / 1000).toFixed(1)}s`,
    "",
    "## Differences by kind",
    "",
    "Each group lists the headings only one engine applied and how the total moved. See PROGRESS.md for the cause of each group.",
    "",
    ...sorted.flatMap(([signature, items]) => [
      `### ${signature}`,
      "",
      `${items.length} calculations. Countries: ${Array.from(new Set(items.map((d) => d.country))).join(", ")}`,
      "",
      "| HTS | Country | Legacy total | v2 total |",
      "|---|---|---|---|",
      ...items.slice(0, 4).map((d) => `| ${d.htsno} | ${d.country} | ${money(d.legacyTotal)} | ${money(d.v2Total)} |`),
      "",
    ]),
  ].join("\n")

  const path = join(__dirname, "..", "..", "tariffs", "engine-v2", "COMPARISON.md")
  writeFileSync(path, report)
  console.log(`${runs} calculations, ${totalsMatch} same total, ${differences.length} with differences, ${groups.size} kinds`)
  console.log(`Report: ${path}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
