export enum NoteType {
  ANY = "any",
  GENERAL = "general",
  SECTION = "section",
  CHAPTER = "chapter",
  SUBCHAPTER = "subchapter",
}

export interface NoteI {
  title: string;
  description: string;
  fileName: string;
  specialTariffTreatmentCodes?: string[];
  type: NoteType;
}

export const notes: NoteI[] = [
  {
    title: "General Rules of Interpretation",
    description: "General Rules of Interpretation",
    fileName: "General Rules of Interpretation",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Statistical Notes",
    description: "General Statistical Notes",
    fileName: "General Statistical Notes",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 1",
    description:
      "Tariff Treatment of Imported Goods and of Vessel Equipments, Parts and Repairs",
    fileName: "General Note 1",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 2",
    description: "Customs Territory of the United States",
    fileName: "General Note 2",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 3",
    description: "Rates of Duty",
    fileName: "General Note 3",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 4",
    description: "Generalized System of Preferences (GSP)",
    fileName: "General Note 4",
    specialTariffTreatmentCodes: ["A", "A*", "A+"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 5",
    description: "Automotive Products Trade Act",
    fileName: "General Note 5",
    specialTariffTreatmentCodes: ["B"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 6",
    description: "Agreement on Trade in Civil Aircraft",
    fileName: "General Note 6",
    specialTariffTreatmentCodes: ["C"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 7",
    description: "Caribbean Basin Economic Recovery Act (CBERA)",
    fileName: "General Note 7",
    specialTariffTreatmentCodes: ["E", "E*"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 8",
    description:
      "United States-Israel Free Trade Area Implementation Act of 1985",
    fileName: "General Note 8",
    specialTariffTreatmentCodes: ["IL"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 9",
    description: "United States-Canada Free-Trade Agreement-Suspended",
    fileName: "General Note 9",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 10",
    description: "Products of the Freely Associated States",
    fileName: "General Note 10",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 11",
    description: "United States-Mexico-Canada Agreement",
    fileName: "General Note 11",
    specialTariffTreatmentCodes: ["S", "S+"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 12",
    description: "North American Free Trade Agreement-Deleted",
    fileName: "General Note 12",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 13",
    description: "Pharmaceutical products and related appendix",
    fileName: "General Note 13",
    specialTariffTreatmentCodes: ["K"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 14",
    description: "Intermediate chemicals for dyes and related appendix",
    fileName: "General Note 14",
    specialTariffTreatmentCodes: ["L"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 15",
    description: "Exclusions from tariff rate quotas",
    fileName: "General Note 15",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 16",
    description: "African Growth and Opportunity Act (AGOA)",
    fileName: "General Note 16",
    specialTariffTreatmentCodes: ["D"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 17",
    description:
      "United States-Caribbean Basin Trade Partnership Act of 2000 (CBPTA)",
    fileName: "General Note 17",
    specialTariffTreatmentCodes: ["R"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 18",
    description: "United States-Jordan Free Trade Area Implementation Act",
    fileName: "General Note 18",
    specialTariffTreatmentCodes: ["JO"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 25",
    description: "United States-Singapore Free Trade Agreement",
    fileName: "General Note 25",
    specialTariffTreatmentCodes: ["SG"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 26",
    description: "United States-Chile Free Trade Agreement",
    fileName: "General Note 26",
    specialTariffTreatmentCodes: ["CL"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 27",
    description: "United States-Morocco Free Trade Agreement",
    fileName: "General Note 27",
    specialTariffTreatmentCodes: ["MA"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 28",
    description: "United States-Australia Free Trade Agreement",
    fileName: "General Note 28",
    specialTariffTreatmentCodes: ["AU"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 29",
    description:
      "Dominican Republic-Central America-United States Free Trade Agreement (DR-CAFTA)",
    fileName: "General Note 29",
    specialTariffTreatmentCodes: ["P", "P+"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 30",
    description: "United States-Bahrain Free Trade Agreement",
    fileName: "General Note 30",
    specialTariffTreatmentCodes: ["BH"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 31",
    description: "United States-Oman Free Trade Agreement",
    fileName: "General Note 31",
    specialTariffTreatmentCodes: ["OM"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 32",
    description: "United States-Peru Trade Promotion Agreement",
    fileName: "General Note 32",
    specialTariffTreatmentCodes: ["PE"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 33",
    description: "United States-Korea Free Trade Agreement",
    fileName: "General Note 33",
    specialTariffTreatmentCodes: ["KR"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 34",
    description: "United States-Colombia Trade Promotion Agreement",
    fileName: "General Note 34",
    specialTariffTreatmentCodes: ["CO"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 35",
    description: "United States-Panama Trade Promotion Agreement",
    fileName: "General Note 35",
    specialTariffTreatmentCodes: ["PA"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 36",
    description: "Trade Agreement between the United States and Japan",
    fileName: "General Note 36",
    specialTariffTreatmentCodes: ["JP"],
    type: NoteType.GENERAL,
  },
  {
    title: "Section 1",
    description: "Live Animals; Animal Products",
    fileName: "Chapter 1",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 2",
    description: "Vegetable Products",
    fileName: "Chapter 6",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 3",
    description:
      "Animal or Vegetable Fats and Oils and Their Cleavage Products; Prepared Edible Fats; Animal or Vegetable Waxes",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 4",
    description:
      "Prepared Foodstuffs; Beverages, Spirits, and Vinegar; Tobacco and Manufactured Tobacco Substitutes",
    fileName: "Chapter 16",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 5",
    description: "Mineral Products",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 6",
    description: "Products of the Chemical or Allied Industries",
    fileName: "Chapter 28",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 7",
    description: "Plastics and Articles Thereof Rubber and Articles Thereof",
    fileName: "Chapter 39",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 8",
    description:
      "Raw Hides and Skins, Leather, Furskins and Articles Thereof; Saddlery and Harness; Travel Goods, Handbags and Similar Containers; Articles of Animal Gut (Other Than Silkworm Gut)",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 9",
    description:
      "Wood and Articles of Wood; Wood Charcoal; Cork and Articles of Cork; Manufacturers of Straw,of Esparto or of Other Plaiting Materials; Basketware and Wickerwork",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 10",
    description:
      "Pulp of Wood or of Other Fibrous Cellulosic Material; Waste and Scrap of Paper or Paperboard; Paper and Paperboard and Articles Thereof",
    fileName: "Chapter 47",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 11",
    description: "Textile and Textile Articles",
    fileName: "Chapter 50",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 12",
    description:
      "Footwear, Headgear, Umbrellas, Sun Umbrellas, Walking Sticks, Seatsticks, Whips, Riding-Crops and Parts Thereof; Prepared Feathers and Articles Made Therewith; Artificial Flowers; Articles of Human Hair",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 13",
    description:
      "Articles of Stone, Plaster, Cement, Asbestos, Mica or Similar Materials; Ceramic Products; Glass and Glassware",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 14",
    description:
      "Natural or Cultured Pearls, Precious or Semiprecious Stones, Precious Metals, Metals Clad With Precious Metal, and Articles Thereof; Imitation Jewelry; Coin",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 15",
    description: "Base Metals and Articles of Base Metal",
    fileName: "Chapter 72",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 16",
    description:
      "Machinery and Mechanical Appliances; Electrical Equipment; Parts Thereof; Sound Recorders and Reproducers, Television Image and Sound Recorders and Reproducers, and Parts and Accessories of Such Articles",
    fileName: "Chapter 84",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 17",
    description:
      "Vehicles, Aircraft, Vessels and Associated Transport Equipment",
    fileName: "Chapter 86",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 18",
    description:
      "Optical, Photographic, Cinematographic, Measuring, Checking, Precision, Medical or Surgical Instruments and Apparatus; Clocks and Watches; Musical Instruments; Parts and Accessories Thereof",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 19",
    description: "Arms and Ammunition; Parts and Accessories Thereof",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 20",
    description: "Miscellaneous Manufactured Articles",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 21",
    description: "Works of Art, Collectors' Pieces and Antiques",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 22",
    description:
      "Special Classification Provisions; Temporary Legislation; Temporary Modifications Proclaimed pursuant to Trade Agreements Legislation; Additional Import Restrictions Proclaimed Pursuant to Section 22 of the Agricultural Adjustment Act, As Amended",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Chapter 1",
    description: "Live animals",
    fileName: "Chapter 1",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 2",
    description: "Meat and edible meat offal",
    fileName: "Chapter 2",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 3",
    description:
      "Fish and crustaceans, molluscs and other aquatic invertebrates",
    fileName: "Chapter 3",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 4",
    description:
      "Dairy produce; birds eggs; natural honey; edible products of animal origin, not elsewhere specified or included",
    fileName: "Chapter 4",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 5",
    description:
      "Products of animal origin, not elsewhere specified or included",
    fileName: "Chapter 5",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 6",
    description:
      "Live trees and other plants; bulbs, roots and the like; cut flowers and ornamental foliage",
    fileName: "Chapter 6",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 7",
    description: "Edible vegetables and certain roots and tubers",
    fileName: "Chapter 7",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 8",
    description: "Edible fruit and nuts; peel of citrus fruit or melons",
    fileName: "Chapter 8",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 9",
    description: "Coffee, tea, maté and spices",
    fileName: "Chapter 9",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 10",
    description: "Cereals",
    fileName: "Chapter 10",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 11",
    description:
      "Products of the milling industry; malt; starches; inulin; wheat gluten",
    fileName: "Chapter 11",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 12",
    description:
      "Oil seeds and oleaginous fruits; miscellaneous grains, seeds and fruits; industrial or medicinal plants; straw and fodder",
    fileName: "Chapter 12",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 13",
    description: "Lac; gums, resins and other vegetable saps and extracts",
    fileName: "Chapter 13",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 14",
    description:
      "Vegetable plaiting materials; vegetable products not elsewhere specified or included",
    fileName: "Chapter 14",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 15",
    description:
      "Animal or vegetable fats and oils and their cleavage products prepared edible fats; animal or vegetable waxes",
    fileName: "Chapter 15",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 16",
    description:
      "Preparations of meat, of fish or of crustaceans, molluscs or other aquatic invertebrates",
    fileName: "Chapter 16",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 17",
    description: "Sugars and sugar confectionery",
    fileName: "Chapter 17",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 18",
    description: "Cocoa and cocoa preparations",
    fileName: "Chapter 18",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 19",
    description:
      "Preparations of cereals, flour, starch or milk; bakers' wares",
    fileName: "Chapter 19",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 20",
    description:
      "Preparations of vegetables, fruit, nuts or other parts of plants",
    fileName: "Chapter 20",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 21",
    description: "Miscellaneous edible preparations",
    fileName: "Chapter 21",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 22",
    description: "Beverages, spirits and vinegar",
    fileName: "Chapter 22",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 23",
    description:
      "Residues and waste from the food industries; prepared animal feed",
    fileName: "Chapter 23",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 24",
    description: "Tobacco and manufactured tobacco substitutes",
    fileName: "Chapter 24",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 25",
    description:
      "Salt; sulfur; earths and stone; plastering materials, lime and cement",
    fileName: "Chapter 25",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 26",
    description: "Ores, slag and ash",
    fileName: "Chapter 26",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 27",
    description:
      "Mineral fuels, mineral oils and products of their distillation; bituminous substances; mineral waxes",
    fileName: "Chapter 27",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 28",
    description:
      "Inorganic chemicals; organic or inorganic compounds of precious metals, of rare-earth metals, of radioactive elements or of isotopes",
    fileName: "Chapter 28",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 29",
    description: "Organic chemicals",
    fileName: "Chapter 29",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 30",
    description: "Pharmaceutical products",
    fileName: "Chapter 30",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 31",
    description: "Fertilizers",
    fileName: "Chapter 31",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 32",
    description:
      "Tanning or dyeing extracts; dyes, pigments, paints, varnishes, putty and mastics",
    fileName: "Chapter 32",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 33",
    description:
      "Essential oils and resinoids; perfumery, cosmetic or toilet preparations",
    fileName: "Chapter 33",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 34",
    description:
      "Soap, organic surface-active agents, washing preparations, lubricating preparations, artificial waxes, prepared waxes, polishing or scouring preparations, candles and similar articles, modeling pastes, 'dental waxes' and dental preparations with a basis of plaster",
    fileName: "Chapter 34",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 35",
    description: "Albuminoidal substances; modified starches; glues; enzymes",
    fileName: "Chapter 35",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 36",
    description:
      "Explosives; pyrotechnic products; matches; pyrophoric alloys; certain combustible preparations",
    fileName: "Chapter 36",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 37",
    description: "Photographic or cinematographic goods",
    fileName: "Chapter 37",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 38",
    description: "Miscellaneous chemical products",
    fileName: "Chapter 38",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 39",
    description: "Plastics and articles thereof",
    fileName: "Chapter 39",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 40",
    description: "Rubber and articles thereof",
    fileName: "Chapter 40",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 41",
    description: "Raw hides and skins (other than furskins) and leather",
    fileName: "Chapter 41",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 42",
    description:
      "Articles of leather; saddlery and harness; travel goods, handbags and similar containers; articles of animal gut (other than silkworm gut)",
    fileName: "Chapter 42",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 43",
    description: "Furskins and artificial fur; manufactures thereof",
    fileName: "Chapter 43",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 44",
    description: "Wood and articles of wood; wood charcoal",
    fileName: "Chapter 44",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 45",
    description: "Cork and articles of cork",
    fileName: "Chapter 45",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 46",
    description:
      "Manufactures of straw, of esparto or of other plaiting materials; basketware and wickerwork",
    fileName: "Chapter 46",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 47",
    description:
      "Pulp of wood or of other fibrous cellulosic material; waste and scrap of paper or paperboard",
    fileName: "Chapter 47",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 48",
    description:
      "Paper and paperboard; articles of paper pulp, of paper or of paperboard",
    fileName: "Chapter 48",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 49",
    description:
      "Printed books, newspapers, pictures and other products of the printing industry; manuscripts, typescripts and plans",
    fileName: "Chapter 49",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 50",
    description: "Silk",
    fileName: "Chapter 50",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 51",
    description:
      "Wool, fine or coarse animal hair; horsehair yarn and woven fabric",
    fileName: "Chapter 51",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 52",
    description: "Cotton",
    fileName: "Chapter 52",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 53",
    description:
      "Other vegetable textile fibers; paper yarn and woven fabric of paper yarn",
    fileName: "Chapter 53",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 54",
    description: "Man-made filaments",
    fileName: "Chapter 54",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 55",
    description: "Man-made staple fibers",
    fileName: "Chapter 55",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 56",
    description:
      "Wadding, felt and nonwovens; special yarns, twine, cordage, ropes and cables and articles thereof",
    fileName: "Chapter 56",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 57",
    description: "Carpets and other textile floor coverings",
    fileName: "Chapter 57",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 58",
    description:
      "Special woven fabrics; tufted textile fabrics; lace, tapestries; trimmings; embroidery",
    fileName: "Chapter 58",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 59",
    description:
      "Impregnated, coated, covered or laminated textile fabrics; textile articles of a kind suitable for industrial use",
    fileName: "Chapter 59",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 60",
    description: "Knitted or crocheted fabrics",
    fileName: "Chapter 60",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 61",
    description:
      "Articles of apparel and clothing accessories, knitted or crocheted",
    fileName: "Chapter 61",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 62",
    description:
      "Articles of apparel and clothing accessories, not knitted or crocheted",
    fileName: "Chapter 62",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 63",
    description:
      "Other made up textile articles; sets; worn clothing and worn textile articles; rags",
    fileName: "Chapter 63",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 64",
    description: "Footwear, gaiters and the like; parts of such articles",
    fileName: "Chapter 64",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 65",
    description: "Headgear and parts thereof",
    fileName: "Chapter 65",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 66",
    description:
      "Umbrellas, sun umbrellas, walking sticks, seatsticks, whips, riding-crops and parts thereof",
    fileName: "Chapter 66",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 67",
    description:
      "Prepared feathers and down and articles made of feathers or of down; artificial flowers; articles of human hair",
    fileName: "Chapter 67",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 68",
    description:
      "Articles of stone, plaster, cement, asbestos, mica or similar materials",
    fileName: "Chapter 68",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 69",
    description: "Ceramic products",
    fileName: "Chapter 69",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 70",
    description: "Glass and glassware",
    fileName: "Chapter 70",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 71",
    description:
      "Natural or cultured pearls, precious or semi-precious stones,precious metals, metals clad with precious metal and articles thereof; imitation jewelry; coin",
    fileName: "Chapter 71",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 72",
    description: "Iron and steel",
    fileName: "Chapter 72",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 73",
    description: "Articles of iron or steel",
    fileName: "Chapter 73",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 74",
    description: "Copper and articles thereof",
    fileName: "Chapter 74",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 75",
    description: "Nickel and articles thereof",
    fileName: "Chapter 75",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 76",
    description: "Aluminum and articles thereof",
    fileName: "Chapter 76",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 77",
    description: "(Reserved for possible future use)",
    fileName: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 78",
    description: "Lead and articles thereof",
    fileName: "Chapter 78",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 79",
    description: "Zinc and articles thereof",
    fileName: "Chapter 79",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 80",
    description: "Tin and articles thereof",
    fileName: "Chapter 80",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 81",
    description: "Other base metals; cermets; articles thereof",
    fileName: "Chapter 81",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 82",
    description:
      "Tools, implements, cutlery, spoons and forks, of base metal; parts thereof of base metal",
    fileName: "Chapter 82",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 83",
    description: "Miscellaneous articles of base metal",
    fileName: "Chapter 83",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 84",
    description:
      "Nuclear reactors, boilers, machinery and mechanical appliances; parts thereof",
    fileName: "Chapter 84",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 85",
    description:
      "Electrical machinery and equipment and parts thereof; sound recorders and reproducers, television image and sound recorders and reproducers, and parts and accessories of such articles",
    fileName: "Chapter 85",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 86",
    description:
      "Railway or tramway locomotives, rolling-stock and parts thereof; railway or tramway track fixtures and fittings and parts thereof; mechanical (including electro-mechanical) traffic signalling equipment of all kinds",
    fileName: "Chapter 86",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 87",
    description:
      "Vehicles other than railway or tramway rolling stock, and parts and accessories thereof",
    fileName: "Chapter 87",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 88",
    description: "Aircraft, spacecraft, and parts thereof",
    fileName: "Chapter 88",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 89",
    description: "Ships, boats and floating structures",
    fileName: "Chapter 89",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 90",
    description:
      "Optical, photographic, cinematographic, measuring, checking, precision, medical or surgical instruments and apparatus; parts and accessories thereof",
    fileName: "Chapter 90",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 91",
    description: "Clocks and watches and parts thereof",
    fileName: "Chapter 91",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 92",
    description: "Musical instruments; parts and accessories of such articles",
    fileName: "Chapter 92",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 93",
    description: "Arms and ammunition; parts and accessories thereof",
    fileName: "Chapter 93",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 94",
    description:
      "Furniture; bedding, mattresses, mattress supports, cushions and similar stuffed furnishings; lamps and lighting fittings, not elsewhere specified or included; illuminated sign illuminated nameplates and the like; prefabricated buildings",
    fileName: "Chapter 94",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 95",
    description:
      "Toys, games and sports requisites; parts and accessories thereof",
    fileName: "Chapter 95",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 96",
    description: "Miscellaneous manufactured articles",
    fileName: "Chapter 96",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 97",
    description: "Works of art, collectors' pieces and antiques",
    fileName: "Chapter 97",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 98",
    description: "Special classification provisions",
    fileName: "Chapter 98",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 99",
    description:
      "Temporary legislation; temporary modifications proclaimed pursuant to trade agreements legislation; additional import restrictions proclaimed pursuant to section 22 of the Agricultural Adjustment Act, as amended",
    fileName: "Chapter 99",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
];
