export enum NoteType {
  ALL = "all",
  GENERAL = "general",
  SECTION = "section",
  CHAPTER = "chapter",
}

export interface Note {
  title: string;
  description: string;
  filePath: string;
  specialTariffTreatmentCodes?: string[];
  type: NoteType;
}

export const notes: Note[] = [
  {
    title: "General Rules of Interpretation",
    description: "General Rules of Interpretation",
    filePath: "/general/General Rules of Interpretation.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Statistical Notes",
    description: "General Statistical Notes",
    filePath: "/general/General Statistical Notes.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 1",
    description:
      "Tariff Treatment of Imported Goods and of Vessel Equipments, Parts and Repairs",
    filePath: "/general/General Note 1.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 2",
    description: "Customs Territory of the United States",
    filePath: "/general/General Note 2.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 3",
    description: "Rates of Duty",
    filePath: "/general/General Note 3.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 4",
    description: "Generalized System of Preferences (GSP)",
    filePath: "/general/General Note 4.pdf",
    specialTariffTreatmentCodes: ["A", "A*", "A+"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 5",
    description: "Automotive Products Trade Act",
    filePath: "/general/General Note 5.pdf",
    specialTariffTreatmentCodes: ["B"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 6",
    description: "Agreement on Trade in Civil Aircraft",
    filePath: "/general/General Note 6.pdf",
    specialTariffTreatmentCodes: ["C"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 7",
    description: "Caribbean Basin Economic Recovery Act (CBERA)",
    filePath: "/general/General Note 7.pdf",
    specialTariffTreatmentCodes: ["E", "E*"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 8",
    description:
      "United States-Israel Free Trade Area Implementation Act of 1985",
    filePath: "/general/General Note 8.pdf",
    specialTariffTreatmentCodes: ["IL"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 9",
    description: "United States-Canada Free-Trade Agreement-Suspended",
    filePath: "/general/General Note 9.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 10",
    description: "Products of the Freely Associated States",
    filePath: "/general/General Note 10.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 11",
    description: "United States-Mexico-Canada Agreement",
    filePath: "/general/General Note 11.pdf",
    specialTariffTreatmentCodes: ["S", "S+"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 12",
    description: "North American Free Trade Agreement-Deleted",
    filePath: "/general/General Note 12.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 13",
    description: "Pharmaceutical products and related appendix",
    filePath: "/general/General Note 13.pdf",
    specialTariffTreatmentCodes: ["K"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 14",
    description: "Intermediate chemicals for dyes and related appendix",
    filePath: "/general/General Note 14.pdf",
    specialTariffTreatmentCodes: ["L"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 15",
    description: "Exclusions from tariff rate quotas",
    filePath: "/general/General Note 15.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 16",
    description: "African Growth and Opportunity Act (AGOA)",
    filePath: "/general/General Note 16.pdf",
    specialTariffTreatmentCodes: ["D"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 17",
    description:
      "United States-Caribbean Basin Trade Partnership Act of 2000 (CBPTA)",
    filePath: "/general/General Note 17.pdf",
    specialTariffTreatmentCodes: ["R"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 18",
    description: "United States-Jordan Free Trade Area Implementation Act",
    filePath: "/general/General Note 18.pdf",
    specialTariffTreatmentCodes: ["JO"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 25",
    description: "United States-Singapore Free Trade Agreement",
    filePath: "/general/General Note 25.pdf",
    specialTariffTreatmentCodes: ["SG"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 26",
    description: "United States-Chile Free Trade Agreement",
    filePath: "/general/General Note 26.pdf",
    specialTariffTreatmentCodes: ["CL"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 27",
    description: "United States-Morocco Free Trade Agreement",
    filePath: "/general/General Note 27.pdf",
    specialTariffTreatmentCodes: ["MA"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 28",
    description: "United States-Australia Free Trade Agreement",
    filePath: "/general/General Note 28.pdf",
    specialTariffTreatmentCodes: ["AU"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 29",
    description:
      "Dominican Republic-Central America-United States Free Trade Agreement (DR-CAFTA)",
    filePath: "/general/General Note 29.pdf",
    specialTariffTreatmentCodes: ["P", "P+"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 30",
    description: "United States-Bahrain Free Trade Agreement",
    filePath: "/general/General Note 30.pdf",
    specialTariffTreatmentCodes: ["BH"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 31",
    description: "United States-Oman Free Trade Agreement",
    filePath: "/general/General Note 31.pdf",
    specialTariffTreatmentCodes: ["OM"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 32",
    description: "United States-Peru Trade Promotion Agreement",
    filePath: "/general/General Note 32.pdf",
    specialTariffTreatmentCodes: ["PE"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 33",
    description: "United States-Korea Free Trade Agreement",
    filePath: "/general/General Note 33.pdf",
    specialTariffTreatmentCodes: ["KR"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 34",
    description: "United States-Colombia Trade Promotion Agreement",
    filePath: "/general/General Note 34.pdf",
    specialTariffTreatmentCodes: ["CO"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 35",
    description: "United States-Panama Trade Promotion Agreement",
    filePath: "/general/General Note 35.pdf",
    specialTariffTreatmentCodes: ["PA"],
    type: NoteType.GENERAL,
  },
  {
    title: "General Note 36",
    description: "Trade Agreement between the United States and Japan",
    filePath: "/general/General Note 36.pdf",
    specialTariffTreatmentCodes: ["JP"],
    type: NoteType.GENERAL,
  },
  {
    title: "Section 1",
    description: "Live Animals; Animal Products",
    filePath: "/sections/Section 1.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 2",
    description: "Vegetable Products",
    filePath: "/sections/Section 2.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 3",
    description:
      "Animal or Vegetable Fats and Oils and Their Cleavage Products; Prepared Edible Fats; Animal or Vegetable Waxes",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 4",
    description:
      "Prepared Foodstuffs; Beverages, Spirits, and Vinegar; Tobacco and Manufactured Tobacco Substitutes",
    filePath: "/sections/Section 4.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 5",
    description: "Mineral Products",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 6",
    description: "Products of the Chemical or Allied Industries",
    filePath: "/sections/Section 6.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 7",
    description: "Plastics and Articles Thereof Rubber and Articles Thereof",
    filePath: "/sections/Section 7.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 8",
    description:
      "Raw Hides and Skins, Leather, Furskins and Articles Thereof; Saddlery and Harness; Travel Goods, Handbags and Similar Containers; Articles of Animal Gut (Other Than Silkworm Gut)",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 9",
    description:
      "Wood and Articles of Wood; Wood Charcoal; Cork and Articles of Cork; Manufacturers of Straw,of Esparto or of Other Plaiting Materials; Basketware and Wickerwork",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 10",
    description:
      "Pulp of Wood or of Other Fibrous Cellulosic Material; Waste and Scrap of Paper or Paperboard; Paper and Paperboard and Articles Thereof",
    filePath: "/sections/Section 10.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 11",
    description: "Textile and Textile Articles",
    filePath: "/sections/Section 11.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 12",
    description:
      "Footwear, Headgear, Umbrellas, Sun Umbrellas, Walking Sticks, Seatsticks, Whips, Riding-Crops and Parts Thereof; Prepared Feathers and Articles Made Therewith; Artificial Flowers; Articles of Human Hair",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 13",
    description:
      "Articles of Stone, Plaster, Cement, Asbestos, Mica or Similar Materials; Ceramic Products; Glass and Glassware",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 14",
    description:
      "Natural or Cultured Pearls, Precious or Semiprecious Stones, Precious Metals, Metals Clad With Precious Metal, and Articles Thereof; Imitation Jewelry; Coin",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 15",
    description: "Base Metals and Articles of Base Metal",
    filePath: "/sections/Section 15.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 16",
    description:
      "Machinery and Mechanical Appliances; Electrical Equipment; Parts Thereof; Sound Recorders and Reproducers, Television Image and Sound Recorders and Reproducers, and Parts and Accessories of Such Articles",
    filePath: "/sections/Section 16.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 17",
    description:
      "Vehicles, Aircraft, Vessels and Associated Transport Equipment",
    filePath: "/sections/Section 17.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 18",
    description:
      "Optical, Photographic, Cinematographic, Measuring, Checking, Precision, Medical or Surgical Instruments and Apparatus; Clocks and Watches; Musical Instruments; Parts and Accessories Thereof",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 19",
    description: "Arms and Ammunition; Parts and Accessories Thereof",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 20",
    description: "Miscellaneous Manufactured Articles",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 21",
    description: "Works of Art, Collectors' Pieces and Antiques",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Section 22",
    description:
      "Special Classification Provisions; Temporary Legislation; Temporary Modifications Proclaimed pursuant to Trade Agreements Legislation; Additional Import Restrictions Proclaimed Pursuant to Section 22 of the Agricultural Adjustment Act, As Amended",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.SECTION,
  },
  {
    title: "Chapter 1",
    description: "Live animals",
    filePath: "/chapters/Chapter 1.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 2",
    description: "Meat and edible meat offal",
    filePath: "/chapters/Chapter 2.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 3",
    description:
      "Fish and crustaceans, molluscs and other aquatic invertebrates",
    filePath: "/chapters/Chapter 3.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 4",
    description:
      "Dairy produce; birds eggs; natural honey; edible products of animal origin, not elsewhere specified or included",
    filePath: "/chapters/Chapter 4.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 5",
    description:
      "Products of animal origin, not elsewhere specified or included",
    filePath: "/chapters/Chapter 5.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 6",
    description:
      "Live trees and other plants; bulbs, roots and the like; cut flowers and ornamental foliage",
    filePath: "/chapters/Chapter 6.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 7",
    description: "Edible vegetables and certain roots and tubers",
    filePath: "/chapters/Chapter 7.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 8",
    description: "Edible fruit and nuts; peel of citrus fruit or melons",
    filePath: "/chapters/Chapter 8.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 9",
    description: "Coffee, tea, maté and spices",
    filePath: "/chapters/Chapter 9.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 10",
    description: "Cereals",
    filePath: "/chapters/Chapter 10.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 11",
    description:
      "Products of the milling industry; malt; starches; inulin; wheat gluten",
    filePath: "/chapters/Chapter 11.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 12",
    description:
      "Oil seeds and oleaginous fruits; miscellaneous grains, seeds and fruits; industrial or medicinal plants; straw and fodder",
    filePath: "/chapters/Chapter 12.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 13",
    description: "Lac; gums, resins and other vegetable saps and extracts",
    filePath: "/chapters/Chapter 13.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 14",
    description:
      "Vegetable plaiting materials; vegetable products not elsewhere specified or included",
    filePath: "/chapters/Chapter 14.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 15",
    description:
      "Animal or vegetable fats and oils and their cleavage products prepared edible fats; animal or vegetable waxes",
    filePath: "/chapters/Chapter 15.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 16",
    description:
      "Preparations of meat, of fish or of crustaceans, molluscs or other aquatic invertebrates",
    filePath: "/chapters/Chapter 16.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 17",
    description: "Sugars and sugar confectionery",
    filePath: "/chapters/Chapter 17.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 18",
    description: "Cocoa and cocoa preparations",
    filePath: "/chapters/Chapter 18.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 19",
    description:
      "Preparations of cereals, flour, starch or milk; bakers' wares",
    filePath: "/chapters/Chapter 19.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 20",
    description:
      "Preparations of vegetables, fruit, nuts or other parts of plants",
    filePath: "/chapters/Chapter 20.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 21",
    description: "Miscellaneous edible preparations",
    filePath: "/chapters/Chapter 21.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 22",
    description: "Beverages, spirits and vinegar",
    filePath: "/chapters/Chapter 22.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 23",
    description:
      "Residues and waste from the food industries; prepared animal feed",
    filePath: "/chapters/Chapter 23.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 24",
    description: "Tobacco and manufactured tobacco substitutes",
    filePath: "/chapters/Chapter 24.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 25",
    description:
      "Salt; sulfur; earths and stone; plastering materials, lime and cement",
    filePath: "/chapters/Chapter 25.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 26",
    description: "Ores, slag and ash",
    filePath: "/chapters/Chapter 26.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 27",
    description:
      "Mineral fuels, mineral oils and products of their distillation; bituminous substances; mineral waxes",
    filePath: "/chapters/Chapter 27.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 28",
    description:
      "Inorganic chemicals; organic or inorganic compounds of precious metals, of rare-earth metals, of radioactive elements or of isotopes",
    filePath: "/chapters/Chapter 28.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 29",
    description: "Organic chemicals",
    filePath: "/chapters/Chapter 29.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 30",
    description: "Pharmaceutical products",
    filePath: "/chapters/Chapter 30.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 31",
    description: "Fertilizers",
    filePath: "/chapters/Chapter 31.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 32",
    description:
      "Tanning or dyeing extracts; dyes, pigments, paints, varnishes, putty and mastics",
    filePath: "/chapters/Chapter 32.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 33",
    description:
      "Essential oils and resinoids; perfumery, cosmetic or toilet preparations",
    filePath: "/chapters/Chapter 33.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 34",
    description:
      "Soap, organic surface-active agents, washing preparations, lubricating preparations, artificial waxes, prepared waxes, polishing or scouring preparations, candles and similar articles, modeling pastes, 'dental waxes' and dental preparations with a basis of plaster",
    filePath: "/chapters/Chapter 34.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 35",
    description: "Albuminoidal substances; modified starches; glues; enzymes",
    filePath: "/chapters/Chapter 35.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 36",
    description:
      "Explosives; pyrotechnic products; matches; pyrophoric alloys; certain combustible preparations",
    filePath: "/chapters/Chapter 36.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 37",
    description: "Photographic or cinematographic goods",
    filePath: "/chapters/Chapter 37.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 38",
    description: "Miscellaneous chemical products",
    filePath: "/chapters/Chapter 38.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 39",
    description: "Plastics and articles thereof",
    filePath: "/chapters/Chapter 39.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 40",
    description: "Rubber and articles thereof",
    filePath: "/chapters/Chapter 40.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 41",
    description: "Raw hides and skins (other than furskins) and leather",
    filePath: "/chapters/Chapter 41.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 42",
    description:
      "Articles of leather; saddlery and harness; travel goods, handbags and similar containers; articles of animal gut (other than silkworm gut)",
    filePath: "/chapters/Chapter 42.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 43",
    description: "Furskins and artificial fur; manufactures thereof",
    filePath: "/chapters/Chapter 43.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 44",
    description: "Wood and articles of wood; wood charcoal",
    filePath: "/chapters/Chapter 44.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 45",
    description: "Cork and articles of cork",
    filePath: "/chapters/Chapter 45.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 46",
    description:
      "Manufactures of straw, of esparto or of other plaiting materials; basketware and wickerwork",
    filePath: "/chapters/Chapter 46.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 47",
    description:
      "Pulp of wood or of other fibrous cellulosic material; waste and scrap of paper or paperboard",
    filePath: "/chapters/Chapter 47.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 48",
    description:
      "Paper and paperboard; articles of paper pulp, of paper or of paperboard",
    filePath: "/chapters/Chapter 48.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 49",
    description:
      "Printed books, newspapers, pictures and other products of the printing industry; manuscripts, typescripts and plans",
    filePath: "/chapters/Chapter 49.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 50",
    description: "Silk",
    filePath: "/chapters/Chapter 50.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 51",
    description:
      "Wool, fine or coarse animal hair; horsehair yarn and woven fabric",
    filePath: "/chapters/Chapter 51.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 52",
    description: "Cotton",
    filePath: "/chapters/Chapter 52.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 53",
    description:
      "Other vegetable textile fibers; paper yarn and woven fabric of paper yarn",
    filePath: "/chapters/Chapter 53.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 54",
    description: "Man-made filaments",
    filePath: "/chapters/Chapter 54.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 55",
    description: "Man-made staple fibers",
    filePath: "/chapters/Chapter 55.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 56",
    description:
      "Wadding, felt and nonwovens; special yarns, twine, cordage, ropes and cables and articles thereof",
    filePath: "/chapters/Chapter 56.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 57",
    description: "Carpets and other textile floor coverings",
    filePath: "/chapters/Chapter 57.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 58",
    description:
      "Special woven fabrics; tufted textile fabrics; lace, tapestries; trimmings; embroidery",
    filePath: "/chapters/Chapter 58.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 59",
    description:
      "Impregnated, coated, covered or laminated textile fabrics; textile articles of a kind suitable for industrial use",
    filePath: "/chapters/Chapter 59.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 60",
    description: "Knitted or crocheted fabrics",
    filePath: "/chapters/Chapter 60.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 61",
    description:
      "Articles of apparel and clothing accessories, knitted or crocheted",
    filePath: "/chapters/Chapter 61.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 62",
    description:
      "Articles of apparel and clothing accessories, not knitted or crocheted",
    filePath: "/chapters/Chapter 62.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 63",
    description:
      "Other made up textile articles; sets; worn clothing and worn textile articles; rags",
    filePath: "/chapters/Chapter 63.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 64",
    description: "Footwear, gaiters and the like; parts of such articles",
    filePath: "/chapters/Chapter 64.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 65",
    description: "Headgear and parts thereof",
    filePath: "/chapters/Chapter 65.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 66",
    description:
      "Umbrellas, sun umbrellas, walking sticks, seatsticks, whips, riding-crops and parts thereof",
    filePath: "/chapters/Chapter 66.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 67",
    description:
      "Prepared feathers and down and articles made of feathers or of down; artificial flowers; articles of human hair",
    filePath: "/chapters/Chapter 67.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 68",
    description:
      "Articles of stone, plaster, cement, asbestos, mica or similar materials",
    filePath: "/chapters/Chapter 68.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 69",
    description: "Ceramic products",
    filePath: "/chapters/Chapter 69.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 70",
    description: "Glass and glassware",
    filePath: "/chapters/Chapter 70.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 71",
    description:
      "Natural or cultured pearls, precious or semi-precious stones,precious metals, metals clad with precious metal and articles thereof; imitation jewelry; coin",
    filePath: "/chapters/Chapter 71.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 72",
    description: "Iron and steel",
    filePath: "/chapters/Chapter 72.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 73",
    description: "Articles of iron or steel",
    filePath: "/chapters/Chapter 73.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 74",
    description: "Copper and articles thereof",
    filePath: "/chapters/Chapter 74.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 75",
    description: "Nickel and articles thereof",
    filePath: "/chapters/Chapter 75.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 76",
    description: "Aluminum and articles thereof",
    filePath: "/chapters/Chapter 76.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 77",
    description: "(Reserved for possible future use)",
    filePath: "",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 78",
    description: "Lead and articles thereof",
    filePath: "/chapters/Chapter 78.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 79",
    description: "Zinc and articles thereof",
    filePath: "/chapters/Chapter 79.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 80",
    description: "Tin and articles thereof",
    filePath: "/chapters/Chapter 80.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 81",
    description: "Other base metals; cermets; articles thereof",
    filePath: "/chapters/Chapter 81.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 82",
    description:
      "Tools, implements, cutlery, spoons and forks, of base metal; parts thereof of base metal",
    filePath: "/chapters/Chapter 82.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 83",
    description: "Miscellaneous articles of base metal",
    filePath: "/chapters/Chapter 83.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 84",
    description:
      "Nuclear reactors, boilers, machinery and mechanical appliances; parts thereof",
    filePath: "/chapters/Chapter 84.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 85",
    description:
      "Electrical machinery and equipment and parts thereof; sound recorders and reproducers, television image and sound recorders and reproducers, and parts and accessories of such articles",
    filePath: "/chapters/Chapter 85.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 86",
    description:
      "Railway or tramway locomotives, rolling-stock and parts thereof; railway or tramway track fixtures and fittings and parts thereof; mechanical (including electro-mechanical) traffic signalling equipment of all kinds",
    filePath: "/chapters/Chapter 86.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 87",
    description:
      "Vehicles other than railway or tramway rolling stock, and parts and accessories thereof",
    filePath: "/chapters/Chapter 87.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 88",
    description: "Aircraft, spacecraft, and parts thereof",
    filePath: "/chapters/Chapter 88.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 89",
    description: "Ships, boats and floating structures",
    filePath: "/chapters/Chapter 89.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 90",
    description:
      "Optical, photographic, cinematographic, measuring, checking, precision, medical or surgical instruments and apparatus; parts and accessories thereof",
    filePath: "/chapters/Chapter 90.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 91",
    description: "Clocks and watches and parts thereof",
    filePath: "/chapters/Chapter 91.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 92",
    description: "Musical instruments; parts and accessories of such articles",
    filePath: "/chapters/Chapter 92.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 93",
    description: "Arms and ammunition; parts and accessories thereof",
    filePath: "/chapters/Chapter 93.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 94",
    description:
      "Furniture; bedding, mattresses, mattress supports, cushions and similar stuffed furnishings; lamps and lighting fittings, not elsewhere specified or included; illuminated sign illuminated nameplates and the like; prefabricated buildings",
    filePath: "/chapters/Chapter 94.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 95",
    description:
      "Toys, games and sports requisites; parts and accessories thereof",
    filePath: "/chapters/Chapter 95.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 96",
    description: "Miscellaneous manufactured articles",
    filePath: "/chapters/Chapter 96.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 97",
    description: "Works of art, collectors' pieces and antiques",
    filePath: "/chapters/Chapter 97.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 98",
    description: "Special classification provisions",
    filePath: "/chapters/Chapter 98.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
  {
    title: "Chapter 99",
    description:
      "Temporary legislation; temporary modifications proclaimed pursuant to trade agreements legislation; additional import restrictions proclaimed pursuant to section 22 of the Agricultural Adjustment Act, as amended",
    filePath: "/chapters/Chapter 99.pdf",
    specialTariffTreatmentCodes: [],
    type: NoteType.CHAPTER,
  },
];
